# Generated by Django 4.2 on 2024-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('genre', models.CharField(choices=[('T', 'Terror'), ('C', 'Comedia'), ('I', 'Infantil'), ('A', 'Acción'), ('D', 'Drama')], max_length=30)),
                ('movie_director', models.CharField(max_length=60)),
                ('publication_year', models.IntegerField(max_length=4)),
                ('sinopsis', models.TextField(max_length=250)),
            ],
        ),
    ]
