# Generated by Django 4.2 on 2024-07-13 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='publication_year',
            field=models.IntegerField(),
        ),
    ]
